name: 'test on pull request'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: src-tauri

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Run cargo check
        run: cargo check
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run rustfmt
        run: cargo fmt --all
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply rustfmt"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Run tests
        run: cargo test
